= Остановить запущеный Wildfly
:hp-tags: знай-свой-инструмент


Очень часто бывает, особенно когда разрабатываешь с помощью какой нибудь IDE, что они запускают Wildfly, а потом теряют к нему соединение. И более того тебе бы нужно остановить его, или передеплоить, но мы получаем ошибку вида:

....
Запуск Сервер приложений WildFly 8.2 final завершился сбоем. Точка присоединения HTTP 8080 уже используется.
....

опа, и чего делать дальше, перезапускать весь комьютер?

Нет! Оказывается всё гораздо проще.

Нужно зайти в директорию, где установле Wildfly в папку `/bin` и запустить `jboss-cli.sh` или `jboss-cli.bat`

....
{JBOSS_HOME}/bin/jboss-cli.sh --connect command=:shutdown
....

А когда сервер настроен на IP адресс, то необходимо использовать следующее

....
{JBOSS_HOME}/bin/jboss-cli.sh --connect controller=<IP>:<port> command=:shutdown
....

Читается это всё на самом деле на сайте с документацией от wildfly
https://community.jboss.org/wiki/JBossAS7UserGuide[JBossAS7UserGuide]
в разделе *Stopping a running instance of standalone server*

