= Кузня, а ведь удобно.
:hp-tags: черновик

Пробую по книжке покачаться до беспрерывной интеграции http://bit.ly/1XLMRZZ[Continuous Enterprise Development in Java _by Andrew Lee Rubinger, Aslak Knutsen_] . И вот там используется кузня. Столько рутины уже автоматизировано. Ведь удобно. Надо покопать дальше. Тут ведь и тестирование интеграционное удобнее. Ну т.е. расписано как сделать.

*Что понравилось:*

 . Описываешь почти человеческим языком
 . Инкрементальное описание проекта
 . Довольно тонкая настройка
 . Выбор реализаций ифреймворков
 . Хорошая подсказка по <TAB>, по ней в основном и учусь.
 . По проекту гуляешь как по структуре каталогов в системе, те половина команд уже получается знаешь.

*Не понравилось:*
_По сколько учусь по книге, то книга устарела. Но и официальный сайт тоже устарел. Приходится идти почти в слепую. В книге описывается версия 1 или 2, на сайте версия 3. То что скачалось jboss IDE там используется 3.0.1 кажется. И оно отличается от версии 3, отсутствуют некоторые свойства._
 
 . Хоть я и выбрал scaffolding faces 2.2, когда сгенерировались вьюхи, там используется JSTL! Хотя и BalusC и официальный Oracle, кажется, уже говорят в фейсах забудьте про JSTL. Там своё уже есть, то и используйте.
 
[NOTE]
====
Вот тут наконец, я нашел правильные команды кузни http://forge.jboss.org/document/hands-on-lab
====
