= Инструментарий для разработки JavaEE
:hp-tags: знай-свой-инструмент

Если вы начинающий java-разработчик, и хотите разрабатывать под *Android* или *Desktop* то в принципе вы не ограниченны в выборе средств, это которые IDE. И чтоб не ходить вокруг да около, единстввенным достойным продуктом для такой разработки является IDE от компании JetBrains — *_Intellij Idea_* _Community Edition_

Но если вы хотите научится разрабатывать *web* ориентированные приложения, сервисы, серверы и тому подобное, то тут начинается самое интересное.

[NOTE]
====
Кстати, не обязательно вы можете учиться, вы например можете работать в какой-нибудь мелкой региональной компании у которой просто тупо нет денег на софт.
====

И вот тут проявляется во всей красе, условия, и объективность.

=== О том как эти условия разыгрались в моём конкретном случае

В целом, все равно выбор не большой, и это ОТЛИЧНО!!!

Я буду рассматривать три редактора:

. Intellij Idea
. NetBeans
. Eclipse


==== Intellij Idea Ultimate

И так. Начнем.

Отличный редактор и всё такое. НО! он платный. Та да! Как написал свыше, если нет денег, то он не подходит.
Да я знаю есть у них там EAP лицензия, которая для тестировщиков, типа. И много народу на ней сидят.
Но! в последнее время у них  эта версия стала 30 днейвнйо, и усе, не получается ее использовать по истечении этих дней.
Да там можно ее сбрасывать этот период и пользоваться дальше. Я сам года 2 так просидел, но, в какой-то определнный момент,
этот трюк перестаёт срабатывать! И всё тут! Хоть что делай, не работает, говорит покупай.

[WARNING]
====
Это очень ломает всю вашу систему разработки, в тот момент когда совсем его не ждешь. И запросто можно потерять несколько часов, а то и дней, пока востановишь работоспособность. 
====

Да а ещё у неё нет нормальной поддержки Redmine и вообще системы тикетов и тасков.

Итог: вообще не подходит! 

==== NetBeans